[package]
org = "admin"
name = "query"
version = "0.1.0"
distribution = "2201.12.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerina"
name="ai"
version="1.0.1"
repository="local"

[[dependency]]
org="ballerinax"
name="ai.pinecone"
version="0.1.0"
repository="local"
